### ISSUE TITLE
[TRACKING] Release of TRPC Client Generator

### ISSUE THREAD

**Issue by polvallverdu** [polvallverdu/trpc-client-dart#2]
I've created this issue to track what needs to be done to release the TRPC client generator

- [x] quicktype doesn't allow to personalize nested types (https://github.com/wosherco/quicktype/commit/6f5bb27c2f8fe9409e25762c9b9fa2a869e5391b)
- [x] JSON Serializable not generating (.g.dart files), which prevents serialization and dezerialization (https://github.com/glideapps/quicktype/issues/2660)
- [x] Models and Routes generators are not matching the class names for inputs and outputs (No issue)
- [x] Routes generator puts wrong path for queries (No issue)
- [x] Add transformers support (https://github.com/wosherco/trpc-extractor/commit/6f3ca2f3b5e9c29c8a61ad5603799b97b65b250e) (No issue)

I think I'm not missing anything...
